sudo: required
services:
  - docker

before_install:
  - docker build -t ravidoc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ravidoc/react-test npm run test

after_success:
  - docker build -t ravidoc/multi-client ./client
  - docker build -t ravidoc/multi-nginx ./nginx
  - docker build -t ravidoc/multi-service ./complex-service/src/main/resources
  - docker build -t ravidoc/multi-worker ./complex-worker/src/main/resources
  # Login CLI and publish images to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ravidoc/multi-client
  - docker push ravidoc/multi-nginx
  - docker push ravidoc/multi-service
  - docker push ravidoc/multi-worker
