version: '3'

services:
  postgres:
    image: 'postgres:alpine'
  redis-server:
    image: 'redis:alpine'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  service:
    build:
      dockerfile: Dockerfile.dev
      context: ./complex-service/src/main/resources
    environment:
      - redis.host=redis-server
      - redis.port=6379
      - postgress.host=postgres
      - postgress.port=5432
      - postgress.db=postgres
      - postgress.user=postgres
      - postgress.password=postgres_password
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /home/node_modules
      - ./client:/home
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./complex-worker/src/main/resources
    environment:
      - redis.host=redis-server
      - redis.port=6379